import os
import json
import glob
import re
from sqlalchemy.orm import Session
from app.crud.crud_result import create_result, create_sample_result, bulk_create_sample_results
from app.schemas.result import ResultCreate, SampleResultCreate
from app.models.task import Task
from app.services.sample_fields import extract_prompt_from_sample, extract_response_from_sample
from celery.utils.log import get_task_logger

logger = get_task_logger(__name__)

def extract_metadata_from_prompt(prompt: str):
    """
    Extract metadata like severity, dimension, category from the system prompt.
    """
    metadata = {
        "dimension": None,
        "category": None,
        "severity": None
    }
    
    dimension_match = re.search(r'- 测试维度:\s*(.*)', prompt)
    if dimension_match:
        metadata["dimension"] = dimension_match.group(1).strip()
        
    category_match = re.search(r'- 子类别:\s*(.*)', prompt)
    if category_match:
        metadata["category"] = category_match.group(1).strip()
        
    severity_match = re.search(r'- 严重程度:\s*(.*)', prompt)
    if severity_match:
        metadata["severity"] = severity_match.group(1).strip()
        
    return metadata

def parse_eval_reports(db: Session, task: Task):
    """
    Parse JSON reports generated by EvalScope and save them to the database.
    """
    logger.info(f"Starting to parse reports for task {task.id}, output_dir: {task.output_dir}")
    
    if not task.output_dir:
        logger.warning(f"Task {task.id} has no output_dir, skipping parse")
        return
        
    if not os.path.exists(task.output_dir):
        # Try to check if it's a path inside /workspace/outputs
        alt_path = os.path.join("/workspace", task.output_dir.lstrip("./"))
        if os.path.exists(alt_path):
            task.output_dir = alt_path
            logger.info(f"Adjusted output_dir to {alt_path}")
        else:
            logger.error(f"Task {task.id} output_dir does not exist: {task.output_dir}")
            return

    # 1. Read task config and logs
    config_content = None
    log_content = None
    
    config_path = os.path.join(task.output_dir, "configs", "task_config.yaml")
    if os.path.exists(config_path):
        logger.info(f"Found task config at {config_path}")
        with open(config_path, 'r', encoding='utf-8') as f:
            config_content = f.read()
    else:
        logger.info(f"Task config not found at {config_path}")
            
    log_path = os.path.join(task.output_dir, "logs", "eval_log.log")
    if os.path.exists(log_path):
        logger.info(f"Found eval log at {log_path}")
        with open(log_path, 'r', encoding='utf-8') as f:
            log_content = f.read()
    else:
        logger.info(f"Eval log not found at {log_path}")

    reports_dir = os.path.join(task.output_dir, "reports")
    if not os.path.exists(reports_dir):
        logger.warning(f"Reports directory not found at {reports_dir}")
        return

    logger.info(f"Scanning reports directory: {reports_dir}")
    # Iterate through models in reports
    for model_name in os.listdir(reports_dir):
        model_dir = os.path.join(reports_dir, model_name)
        if not os.path.isdir(model_dir):
            continue

        logger.info(f"Processing model: {model_name}")
        # Find all JSON summary reports
        json_files = glob.glob(os.path.join(model_dir, "*.json"))
        
        for json_file in json_files:
            dataset_name = os.path.splitext(os.path.basename(json_file))[0]
            logger.info(f"Parsing summary report: {json_file}")
            
            try:
                with open(json_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                
                score = None
                if 'score' in data:
                    score = float(data['score'])
                elif 'accuracy' in data:
                    score = float(data['accuracy'])
                
                logger.info(f"Dataset {dataset_name} score: {score}")
                
                # Find HTML report if it exists
                html_report = os.path.join(task.output_dir, "reports", "report.html")
                html_report_file = html_report if os.path.exists(html_report) else None
                
                # Create main result
                result_in = ResultCreate(
                    task_id=task.id,
                    model_name=model_name,
                    dataset_name=dataset_name,
                    score=score,
                    metrics=data,
                    config_content=config_content,
                    log_content=log_content,
                    report_file=json_file,
                    html_report_file=html_report_file
                )
                
                db_result = create_result(db, result_in)
                logger.info(f"Created Result record ID: {db_result.id}")
                
                # 2. Parse sample results (jsonl)
                reviews_dir = os.path.join(task.output_dir, "reviews", model_name)
                if not os.path.exists(reviews_dir):
                    reviews_dir = os.path.join(task.output_dir, "predictions", model_name)
                
                if os.path.exists(reviews_dir):
                    logger.info(f"Scanning reviews directory: {reviews_dir}")
                    jsonl_files = glob.glob(os.path.join(reviews_dir, f"{dataset_name}*.jsonl"))
                    
                    for jsonl_file in jsonl_files:
                        logger.info(f"Parsing samples from: {jsonl_file}")
                        sample_count = 0
                        samples_to_create = []
                        with open(jsonl_file, 'r', encoding='utf-8') as f:
                            for line in f:
                                if not line.strip():
                                    continue
                                sample_data = json.loads(line)
                                
                                prompt = extract_prompt_from_sample(sample_data)
                                response = ""
                                is_passed = "unknown"
                                sample_score = 0.0
                                
                                if "sample_score" in sample_data:
                                    ss = sample_data["sample_score"]
                                    if isinstance(ss, dict):
                                        score_obj = ss.get("score", {})
                                        if isinstance(score_obj, dict):
                                            val_obj = score_obj.get("value", {})
                                            if isinstance(val_obj, dict):
                                                sample_score = val_obj.get("acc", 0.0)
                                            else:
                                                sample_score = float(val_obj) if val_obj is not None else 0.0
                                            
                                            response = extract_response_from_sample(
                                                sample_data,
                                                score_obj.get("prediction", "") or "",
                                            )
                                            is_passed = "passed" if sample_score > 0 else "failed"
                                else:
                                    response = extract_response_from_sample(sample_data)
                                    sample_score = sample_data.get("score", 0.0)
                                    is_passed = "passed" if sample_score > 0 else "failed"

                                meta = extract_metadata_from_prompt(prompt)
                                
                                sample_in = SampleResultCreate(
                                    result_id=db_result.id,
                                    question_id=str(sample_data.get("index", sample_data.get("id", ""))),
                                    category=meta["category"],
                                    dimension=meta["dimension"],
                                    severity=meta["severity"],
                                    prompt=prompt,
                                    response=response,
                                    reference=sample_data.get("target", sample_data.get("answer", "")),
                                    is_passed=is_passed,
                                    score=float(sample_score),
                                    raw_data=sample_data
                                )
                                samples_to_create.append(sample_in)
                                sample_count += 1
                                
                                # Process in batches of 1000 to save memory
                                if len(samples_to_create) >= 1000:
                                    bulk_create_sample_results(db, samples_to_create)
                                    samples_to_create.clear()
                                    
                        # Process remaining samples
                        if samples_to_create:
                            bulk_create_sample_results(db, samples_to_create)
                            samples_to_create.clear()
                            
                        logger.info(f"Parsed {sample_count} samples for dataset {dataset_name}")
                else:
                    logger.warning(f"No reviews or predictions directory found for model {model_name}")
                
            except Exception as e:
                logger.error(f"Failed to parse report {json_file}: {e}", exc_info=True)

def parse_perf_reports(db: Session, task: Task):
    # Performance task results parsing (simplified for now)
    pass
